/**
 * The market — the companies.
 *
 * These are real businesses a middle schooler has heard of, described with
 * exactly the four numbers they already use for their own stand: what it
 * sells, what it keeps, what slice that is, and what the market is asking for
 * each dollar of it.
 *
 * ---------------------------------------------------------------------------
 * DATA PROVENANCE
 *
 * Every figure below now comes from `market-data.json`, which is generated by
 * `scripts/fetch-market-data.mjs` from two free sources:
 *
 *  - **Fundamentals — SEC EDGAR XBRL company facts.** Revenue, net income and
 *    diluted share count as filed in each company's own 10-K. Official, no API
 *    key, no terms problem: these are the numbers the company told the
 *    regulator.
 *  - **Prices — real weekly adjusted closes**, five years of them, on a single
 *    shared date axis so a market-wide fall lands on every company in the same
 *    week.
 *
 * The fetch runs at build time, so there is no API key in the browser and no
 * request from a child's device to a third party. A scheduled daily build is
 * what keeps it current, and `asOf` is shown wherever the numbers appear.
 *
 * Nothing here is rounded for convenience or invented for a lesson. That
 * matters more than it sounds: the whole product rests on "the numbers are
 * always real", and it used to be the one place that was not true.
 * ---------------------------------------------------------------------------
 */

import DATA from './market-data.json';
import { plural } from './copy';

/** The date of the most recent real weekly close in the bundled data. */
export const SNAPSHOT_AS_OF: string = DATA.asOf;
export const FUNDAMENTALS_SOURCE: string = DATA.fundamentalsSource;
export const PRICES_SOURCE: string = DATA.pricesSource;

/** The shared weekly date axis, oldest first. */
export const WEEK_DATES: string[] = DATA.weeks;

/**
 * How the money actually arrives.
 *
 * "They sell things" is where most kids stop, and it is why a P/E of 12 and a
 * P/E of 45 read as the same kind of fact to them. Two companies with identical
 * profit can be worth very different amounts because one has to win its
 * customers again every month and the other does not — which is exactly what
 * the kid felt when their own round earned a higher multiple at the sale.
 */
export type BusinessModel =
  | 'one-off'
  | 'subscription'
  | 'membership'
  | 'platform'
  | 'brand'
  | 'many-copies'
  | 'advertising'
  | 'toll-booth'
  | 'picks-and-shovels';

export const MODELS: Record<
  BusinessModel,
  { name: string; standVersion: string; effect: string }
> = {
  'one-off': {
    name: 'One-off sale',
    standVersion: 'a cup to a stranger walking past',
    effect: 'Good money per sale, but every customer has to be won again.',
  },
  subscription: {
    name: 'Subscription',
    standVersion: 'your round — a cup a day, signed up in advance',
    effect: 'The money arrives whether or not they think about it. Priced higher for exactly that reason.',
  },
  membership: {
    name: 'Membership',
    standVersion: 'charging a season fee for the park pitch',
    effect: 'Almost no profit on the goods. The fee is the business.',
  },
  platform: {
    name: 'Platform',
    standVersion: 'letting someone else sell from your table for a cut',
    effect: 'Grows fast because other people do the work. Often spends more than it earns for years.',
  },
  brand: {
    name: 'Brand',
    standVersion: 'the sign and the fresh-squeezed jug nobody can copy',
    effect: 'Charges more for a nearly identical thing. That gap is the moat.',
  },
  'many-copies': {
    name: 'Many copies',
    standVersion: 'opening a second stand in the park',
    effect: 'Growth is arithmetic: one more of the same, again. Slows the day it runs out of corners.',
  },
  advertising: {
    name: 'Advertising',
    standVersion: 'letting the ice-cream van pin a flyer to your table for a fee',
    effect: 'The person drinking the lemonade is not the one paying you. Worth knowing whose customer you actually are.',
  },
  'toll-booth': {
    name: 'Toll booth',
    standVersion: 'taking two cents every time anyone on the street buys anything',
    effect: 'A tiny slice of an enormous number. Grows with the street rather than with any one stand.',
  },
  'picks-and-shovels': {
    name: 'Picks and shovels',
    standVersion: 'selling lemons and cups to every other stand on the road',
    effect: 'You do not have to pick the winner. You are paid by whoever is digging.',
  },
};

/**
 * How far into the market a company sits.
 *
 * Eight companies was the right number for a first visit and the wrong number
 * for a game somebody keeps playing. A kid who wants to look up a company they
 * care about and cannot find it has been told the market is a fixed menu, which
 * is both untrue and uninteresting.
 *
 * So the market is a collection, and it opens up the way a card game's does.
 * Tier 1 is what a kid physically touches. Tier 2 is what their family spends
 * money on. Tier 3 is the businesses you cannot see from the street and have to
 * read about — an advertising business, a toll booth, a company that sells
 * shovels to everybody else. That order is pedagogical, not arbitrary: you can
 * form a view about Nike by looking at your own feet, and you cannot do that
 * with Visa.
 *
 * Gated on badges rather than on time played, so it is earned rather than
 * waited out.
 */
export type Tier = 1 | 2 | 3;

/**
 * The shelves, and what opens them.
 *
 * `opensAt` is measured in *standing* — badges plus words plus companies read,
 * see `standing()` in `src/lib/career.ts` — and not in badges. It was called
 * `badgesNeeded` and gated on standing everywhere, which meant the trophy case
 * and the market disagreed about which shelves were open and the label under a
 * padlock quoted a number the kid could not find anywhere else.
 */
export const TIERS: Record<Tier, { name: string; blurb: string; opensAt: number }> = {
  1: {
    name: 'Things you use',
    blurb: 'Businesses you can form a view about by looking around your own house.',
    opensAt: 0,
  },
  2: {
    name: 'Where the money goes',
    blurb: 'The ones your family actually spends money on.',
    opensAt: 8,
  },
  3: {
    name: 'You have to read about these',
    blurb: 'Businesses you cannot see from the street. This is where reading the accounts stops being optional.',
    opensAt: 16,
  },
};

/** `standing`, not badges. See `TIERS`. */
export function tierUnlocked(tier: Tier, standing: number): boolean {
  return standing >= TIERS[tier].opensAt;
}


/**
 * One fiscal year, as it was published.
 *
 * `filedOn` is the date the 10-K carrying these figures became public, taken
 * from the first filing that reported them. The market replays a real past week, so
 * the game shows whichever year was actually public then — otherwise the kid
 * gets accounts nobody had yet, and a P/E that mixes a price from one year with
 * earnings from another.
 */
export interface Fundamentals {
  fiscalYear: string;
  fiscalYearEnd: string;
  filedOn: string;
  revenueM: number;
  netIncomeM: number;
  sharesM: number;
  /** Three-year compound profit growth as at this year. */
  growth: number;
  /** Three-year compound revenue growth as at this year. */
  revenueGrowth: number;
}

export interface Company {
  ticker: string;
  name: string;
  emoji: string;
  /** Which part of the collection this belongs to. See `TIERS`. */
  tier: Tier;
  /** What a kid would recognise it for. */
  whatTheySell: string;
  /** Annual revenue, in millions of dollars. */
  revenueM: number;
  /** Annual net income, in millions. Negative means it loses money. */
  netIncomeM: number;
  /** Shares outstanding, in millions. */
  sharesM: number;
  /** Price per share, dollars. */
  price: number;
  /**
   * Profit growth as a three-year compound rate.
   *
   * Compound rather than year-on-year for a reason worth keeping: on real
   * figures, one recovery year showed Disney "growing 149% a year" and two flat
   * years showed Chipotle at 0% despite nearly doubling over three. Neither is
   * something a kid should reason from.
   */
  growth: number;
  /**
   * Revenue growth, same basis. The only growth figure that means anything for
   * a company that does not make a profit yet.
   */
  revenueGrowth: number;
  /** How jumpy the share price is, week to week. */
  volatility: number;
  /** One line a kid can actually reason about. Qualitative, not a hint. */
  story: string;
  /** How the money arrives, mapped to something they did at the stand. */
  model: BusinessModel;

  /* ---- Provenance, so every figure can be traced to a filing ---- */

  /** Fiscal year the fundamentals come from, e.g. "2025". */
  fiscalYear: string;
  /** The exact period end date of that fiscal year. */
  fiscalYearEnd: string;
  /** When the 10-K carrying these figures was filed. */
  filedOn: string;

  /**
   * Five years of real weekly adjusted closes, oldest first, aligned to
   * `WEEK_DATES`. The market replays a hidden stretch of these.
   */
  closes: number[];

  /** Every fiscal year on file, oldest first. */
  annuals: Fundamentals[];
}

/**
 * The eight companies, built from the fetched data.
 *
 * Chosen so the contrasts do the teaching, and the real figures still deliver
 * every one of them:
 *
 *  - COST sells nearly six times what CMG does and keeps about 3c per dollar
 *  - RBLX is beloved by exactly this audience and loses money, so it has no P/E
 *  - KO grows slowly and is priced calmly; CMG grows and is priced dearly
 *
 * The narrative fields — what a kid would recognise it for, the one qualitative
 * line, the business model — are the only things a data feed cannot supply, so
 * they live in the fetch script next to the ticker they belong to.
 */
export const SNAPSHOT: Company[] = DATA.companies.map((row) => ({
  ticker: row.ticker,
  name: row.name,
  emoji: row.emoji,
  tier: (row.tier ?? 1) as Tier,
  whatTheySell: row.whatTheySell,
  revenueM: row.revenueM,
  netIncomeM: row.netIncomeM,
  sharesM: row.sharesM,
  price: row.price,
  growth: row.growth,
  revenueGrowth: row.revenueGrowth,
  volatility: row.volatility,
  story: row.story,
  model: row.model as BusinessModel,
  fiscalYear: row.fiscalYear,
  fiscalYearEnd: row.fiscalYearEnd,
  filedOn: row.filedOn,
  closes: row.closes,
  annuals: row.annuals as Fundamentals[],
}));

/**
 * The accounts that were public on a given date.
 *
 * Without a date, the newest. With one, the most recent 10-K filed on or before
 * it — which is exactly what somebody standing in that week could have read.
 * Before the first filing in the file, the earliest available, because showing
 * nothing would be worse than showing the oldest real figures.
 */
export function fundamentalsAsOf(company: Company, asOf?: string): Fundamentals {
  const years = company.annuals;
  if (years.length === 0) {
    return {
      fiscalYear: company.fiscalYear,
      fiscalYearEnd: company.fiscalYearEnd,
      filedOn: company.filedOn,
      revenueM: company.revenueM,
      netIncomeM: company.netIncomeM,
      sharesM: company.sharesM,
      growth: company.growth,
      revenueGrowth: company.revenueGrowth,
    };
  }
  if (!asOf) return years[years.length - 1];

  let chosen = years[0];
  for (const year of years) {
    if (year.filedOn <= asOf) chosen = year;
  }
  return chosen;
}

/**
 * The first week where every company has published accounts.
 *
 * Roblox listed part-way through the price history, so its first 10-K lands
 * months after the earliest close in the file. Replaying a week before that
 * would mean showing a kid a set of accounts that did not exist yet — so those
 * weeks are simply not offered, which removes the problem rather than
 * documenting an exception to it.
 */
export const FIRST_HONEST_WEEK: number = (() => {
  /*
   * Tier 1 only, and that is a change worth explaining.
   *
   * This used to take the latest first-filing across every company, so a single
   * recent flotation shortened the playable history for everybody: adding
   * Duolingo and DoorDash to the roster cut it from five years to two and a
   * half, which quietly halved the number of twelve-week windows and made real
   * market falls rarer in the game than they are in life.
   *
   * The honest fix is not to move the line, it is to stop showing a company
   * before it existed. So the window is bounded by the eight companies every
   * kid sees from their first week, and anything later-listed is simply absent
   * from the market until the week its first accounts were public — see
   * `hasAccountsBy`.
   */
  const firstFilings = DATA.companies
    .filter((company) => (company.tier ?? 1) === 1 && company.annuals.length > 0)
    .map((company) => company.annuals[0].filedOn);
  const latestFirstFiling = firstFilings.sort().pop() ?? '0000-00-00';
  const index = DATA.weeks.findIndex((date) => date >= latestFirstFiling);
  return index < 0 ? 0 : index;
})();

/**
 * Was this company public, with accounts a kid could have read, by this date?
 *
 * The market replays a real week. Offering Duolingo in a week before it floated
 * would be offering a share nobody could have bought, priced off accounts
 * nobody had seen.
 */
export function hasAccountsBy(company: Company, asOf?: string): boolean {
  if (!asOf) return true;
  const first = company.annuals[0];
  return Boolean(first && first.filedOn <= asOf);
}

/** Real weekly closes for one company, aligned to `WEEK_DATES`. */
export function closesFor(ticker: string): number[] {
  return SNAPSHOT.find((company) => company.ticker === ticker)?.closes ?? [];
}

/* ------------------------------------------------------------------ *
 * The same four numbers the kid used for their own stand
 * ------------------------------------------------------------------ */

export interface CompanyMetrics {
  /** Profit per share for a year. */
  eps: number | null;
  /** Total price of the whole company, in millions. */
  marketCapM: number;
  /** Price divided by yearly profit per share. Null when it loses money. */
  pe: number | null;
  /** What fraction of revenue it keeps. */
  netMargin: number;
  /** Years of profit before you have your money back. Same as PE. */
  paybackYears: number | null;
  /** Flip the multiple: profit per year as a percentage of the price. */
  earningsYield: number | null;
  profitable: boolean;
  /** The fiscal year these came from, so the card can name it. */
  year: Fundamentals;
}

/**
 * The four numbers, at a given price.
 *
 * `price` is a parameter and not just `company.price` because the market replays a
 * real stretch of history: the kid is looking at, and paying, the price from
 * *that* week. Computing the P/E off today's price while they trade a
 * historical one produced a card where the price and the multiple came from
 * different years — arithmetically fine, and a lie.
 */
export function metricsFor(
  company: Company,
  price = company.price,
  asOf?: string,
): CompanyMetrics {
  const year = fundamentalsAsOf(company, asOf);
  const marketCapM = price * year.sharesM;
  const profitable = year.netIncomeM > 0;
  const eps = year.sharesM > 0 ? year.netIncomeM / year.sharesM : null;
  const pe = profitable && eps && eps > 0 ? price / eps : null;

  return {
    eps,
    marketCapM,
    pe,
    netMargin: year.revenueM > 0 ? year.netIncomeM / year.revenueM : 0,
    paybackYears: pe,
    earningsYield: pe ? 1 / pe : null,
    profitable,
    year,
  };
}

export function findCompany(ticker: string): Company | undefined {
  return SNAPSHOT.find((c) => c.ticker === ticker);
}

/** Formats a big number the way a kid can read it aloud. */
export function formatMillions(millions: number): string {
  const abs = Math.abs(millions);
  const sign = millions < 0 ? '-' : '';
  if (abs >= 1_000_000) return `${sign}$${(abs / 1_000_000).toFixed(1)}T`;
  if (abs >= 1_000) return `${sign}$${(abs / 1_000).toFixed(abs >= 10_000 ? 0 : 1)}B`;
  return `${sign}$${abs.toFixed(0)}M`;
}

/**
 * The bridge sentence, per company: their stand, restated at scale.
 *
 * Generated rather than written, so it always matches the data.
 */
export function standComparison(company: Company, price = company.price, asOf?: string): string {
  const m = metricsFor(company, price, asOf);
  const keeps = `${(m.netMargin * 100).toFixed(0)}c of every dollar`;
  if (!m.profitable) {
    return `${company.name} takes in ${formatMillions(m.year.revenueM)} a year and still loses money. It has no P/E, because there are no earnings to divide by.`;
  }
  return `${company.name} sells ${formatMillions(m.year.revenueM)} a year and keeps ${keeps}. At ${plural(Number(m.pe!.toFixed(0)), 'time')} yearly profit, you would wait ${m.pe!.toFixed(0)} years to get your money back.`;
}
